### PR TITLE
APEXMALHAR-2122 Upgrading elasticsearch java api from 1.1.2 to 2.3.3.

### PR DESCRIPTION
**Pull request by akshay-harale**
Upgrading elasticsearch java api from 1.1.2 to 2.3.3. Made necessary changes in operator. Fixed build issues recognised while migration.

@gauravgopi123 you can close [old PR](https://github.com/apache/apex-malhar/pull/325), this is created with jira issue id as branch name.

### CODE REVIEW

**Comment by akshay-harale** [comment]
Comment Copied from old PR : 
Use case is something like this, we were trying to dig into the data using Apex library and that data we wanted to visualise using Kibana dashboard. Kibana Dashboard uses Elastic Search to optimize and provide search on the data also let's us apply the filters. So I wanted to push data using elastic search operator available through Apex malhar and unfortunately that didn't work, was getting issues connecting to elastic search cluster. Then I tried posting the question on apex user forum, which didn't receive any response, so I went ahead and updated the elastic search version in Apex Malhar. This resulted in seamless connection and loading of data in the elastic search clusters through Apex. And that's the sole reason I feel we should update elastic search library being used in apex to latest version available.

**Comment by tweise** [comment]
@akshay-harale only you can close the old PR #325 

Which tests have you executed?

Please also rebase this PR (pull master branch and the run `git rebase apache/master` 
see http://apex.apache.org/contributing.html#opening-pull-requests-contributors-

**Comment by ilganeli** [comment]
@akshay-harale Is this PR still relevant?

**Comment by vrozov** [comment]
@akshay-harale closed due to inactivity

**Pull request closed without merging**
