### PR TITLE
APEXMALHAR-2171 #resolve #comment Added methoed call to set maxCacheS…

### PR DESCRIPTION
**Pull request by ShunxinLu**
…ize when building cache.

### CODE REVIEW

**Comment by siyuanh** [comment]
@chandnisingh  Could you please review this? Is it the only place we need to use the maxSize?

**Comment by otterc** [comment]
LGTM
Typo in the commit comment.

**Comment by ShunxinLu** [comment]
@chandnisingh Thank you for pointing out, will be fixed in a moment.

**Comment by otterc** [comment]
There is still a typo - "buiding"

**Pull request merged**
