### PR TITLE
APEXMALHAR-2343 Count fix and accumulation input parameter type change 

### PR DESCRIPTION
**Pull request by davidyan74**
@brightchen @chinmaykolhatkar @siyuanh  Please have a look

### CODE REVIEW

**Comment by chinmaykolhatkar** [comment]
LGTM.

**Comment by chinmaykolhatkar** [comment]
@davidyan74 The changes looks good to me. Can you rebase and squash?
The test failure doesn't seem to be related to these code changes, hence I think the PR can be merged, unless anyone sees any issues.

**Comment by siyuanh** [comment]
@davidyan74 @brightchen  In ApexWindowedStreamImpl line 88. If you always increase the count by 1 you don't need that map function

**Comment by davidyan74** [comment]
@siyuanh I have changed ApexWindowedStreamImpl to use SumLong instead of Count. I don't want to remove the map function because it actually does something other than mapping to 1. It actually adds the current timestamp if the timestamp does not already exist. And by the way, I think the automatic adding of the timestamp may break idempotency. In any case, it's not the scope of this PR.

**Comment by davidyan74** [comment]
@siyuanh If this looks fine with you, please merge. The Count accumulation is no longer used anywhere within Malhar.

**Comment by davidyan74** [comment]
@siyuanh please review and merge when you have a chance. This is blocking some other PRs. Thanks.

**Comment by siyuanh** [comment]
@davidyan74 Just reviewed and rebased yesterday, will merge it today

**Pull request merged**
