### PR TITLE
MLHR-1919 #resolve #comment add dimension schema to malhar

### PR DESCRIPTION
**Pull request by brightchen**

### CODE REVIEW

**Comment by brightchen** [comment]
@ilooner please review and merge

**Comment by ilooner** [comment]
@brightchen Thanks for doing this move. My only comment is that the package for the classes should start with org.apache.apex.malhar instead of com.datatorrent.lib

That's it. Thanks!

**Comment by tweise** [comment]
@ilooner Agreed. Can you please pull in the changes and then we do the rename in a separate PR.

**Comment by tweise** [comment]
@ilooner can this be merged?

**Pull request merged**
