### PR TITLE
APEXMALHAR-2158 Fixed the duplication of messages emitted issue when the Kafka Input operator redeployed

### PR DESCRIPTION
**Pull request by chaithu14**

### CODE REVIEW

**Comment by chaithu14** [comment]
@siyuanh : Please review and merge.

**Comment by siyuanh** [comment]
@chaithu14 Looks good to me, but can you write a unit test to verify this（just checkpoint the offset and redeploy the operator to make sure there is duplication or data loss）? And did you verify the duplicate you see is always just one tuple?

**Comment by chaithu14** [comment]
@siyuanh Sure. I will write the unit test for this fix. 
Yes I verified, the duplicate is just one tuple and this depends on number of topic partitions.

**Comment by chaithu14** [comment]
@siyuanh Added unit test case and updated the PR.

**Pull request merged**
