### PR TITLE
APEXMALHAR-1980: Adding auto metrics to Cassandra Input Operator

### PR DESCRIPTION
**Pull request by DT-Priyanka**
@bhupeshchawda please review.

### CODE REVIEW

**Comment by bhupeshchawda** [comment]
Change looks good to me. I'll merge this tomorrow if there are no other comments.

**Comment by sandeshh** [comment]
How this is different than the platform provided count for tuples from each operator?

**Comment by DT-Priyanka** [comment]
If a operator dies, the count provided as tuples count may not be right, that's why we use autometrics here.

**Comment by tweise** [comment]
@DT-Priyanka please rebase, I will merge it.

**Comment by tweise** [comment]
@DT-Priyanka any update on this?

**Comment by DT-Priyanka** [comment]
Opening new pull request against mater branch.

**Pull request closed without merging**
