### PR TITLE
APEXMALHAR-2143 - Evaluate and retire lib/math, lib/algo, and lib/streamquery operators

### PR DESCRIPTION
**Pull request by prasannapramod**
@davidyan74 @PramodSSImmaneni @tweise  please review . I am working on fixing the functionality of the operators like "BottomNUniqueMap" , "InsertSort", "TopN", "UniqueCounter", "MarginKeyVal" . Also, I am planning to reimplement some operators like "BottomNMap" using the windows operator and managed state .

### CODE REVIEW

**Comment by davidyan74** [comment]
it looks good to me. @PramodSSImmaneni and @tweise  any comments?

**Comment by tweise** [comment]
Please rebase the PR to apache:master and change the PR with exact JIRA number:
http://apex.apache.org/contributing.html#opening-pull-requests-contributors-

**Comment by prasannapramod** [comment]
Changed PR title to include exact JIRA number, rebased to latest master, made improvements to Average, Distinct and FilterValues operators.

**Comment by tweise** [comment]
Can you close/reopen to trigger the CI again?

**Comment by prasannapramod** [comment]
@tweise I ran the build using command
 "mvn clean install -Pall-modules" . it executed successfully, but for some reason its failing here.

**Pull request merged**
