### PR TITLE
APEXMALHAR-2457 Remove duplicate entries

### PR DESCRIPTION
**Pull request by amberarrow**
Fixed duplicate entries.
@tweise please take a look.

### CODE REVIEW

**Comment by trusli** [comment]
"Jdbc Output Operator" can use typo correction to "JDBC"

**Comment by amberarrow** [comment]
@trusli Changed Jdbc to all uppercase

**Comment by amberarrow** [comment]
Closed by mistake, reopening.

**Comment by tweise** [comment]
LGTM @amberarrow please merge it

**Comment by tweise** [comment]
@amberarrow the contributor guidelines suggest that a PR is rebased to head of remote before merging whenever practical. In this case it was even yourself merging it, so I would expect that to happen and not see the extra merge commit.

**Pull request merged**
