### PR TITLE
MLHR-1944 #comment Added from previous release

### PR DESCRIPTION
**Pull request by brightchen**
@ilooner @chandnisingh please review and merge

### CODE REVIEW

**Comment by otterc** [comment]
are there tests for it too?

**Comment by otterc** [comment]
Just want to make sure if we missed moving the tests. If there weren't any tests it is still file.

**Comment by brightchen** [comment]
DimensionsConversionContext is a class, but in fact don't have any logic, only properties.
I don't find any test case related to it.

**Comment by ilooner** [comment]
@brightchen There are some for CustomTimeBucketRegistry and DimensionsDescriptor

**Comment by brightchen** [comment]
@ilooner why the tester in different package? which package make more sense, dimensions or appdata/dimensions?
bright-mac:Megh bright$ find . -iname "CustomTimeBucketRegistry*.java"
./library/src/main/java/com/datatorrent/lib/dimensions/CustomTimeBucketRegistry.java
./library/src/test/java/com/datatorrent/lib/appdata/dimensions/CustomTimeBucketRegistryTest.java

**Comment by ilooner** [comment]
@brightchen Good point, I agree they should be in the same package. I made the mistake of putting them in different packages.

**Comment by ilooner** [comment]
@brightchen please remove @since tags in the java doc at the top of the class in CustomTimeBucketRegistry and DimensionsDescriptor. Those will be inserted by the release process. Otherwise looks good and I will merge after that.

**Comment by brightchen** [comment]
@ilooner the @since tags had removed, please merge

**Pull request merged**
