### PR TITLE
APEXMALHAR-1990

### PR DESCRIPTION
**Pull request by pramodin**
Fix for concurrent modification exceptions when deleting old idempotent state. @amberarrow @chandnisingh please review

### CODE REVIEW

**Comment by otterc** [comment]
Pramod can you please also fix WindowDataManager.

**Comment by pramodin** [comment]
Will do Chandni.

Thanks for the suggestion.

On Feb 5, 2016, at 10:15 PM, Chandni Singh notifications@github.com wrote:

Pramod can you please also fix WindowDataManager.

**Comment by pramodin** [comment]
Didn't fix the html javadoc formatting as we can do it uniformly across all files as a group later. Addressed all other comments.

**Comment by tweise** [comment]
Saw following intermittent test failure:

```
Failed tests: 
  JMSOutputOperatorTest.testAtMostOnceHalfBatch:669 Batch should be written expected:<10> but was:<0>
```

**Pull request merged**
