### PR TITLE
APEXMALHAR-2128 Updated twitter4j library to 4.0.4

### PR DESCRIPTION
**Pull request by chinmaykolhatkar**
@PramodSSImmaneni Can you please review and merge?

### CODE REVIEW

**Comment by gauravgopi123** [comment]
@chinmaykolhatkar : I see there is big jump from 2.2.6 to 4.0.4. What new features are you using from new version? Jira doesn't say anything..

**Comment by pramodin** [comment]
@gauravgopi123 That api doesn't work anymore and is eol'ed. Twitter seems to be turning off older web services as newer ones are released. It is easier to keep up by going with the latest.

**Comment by gauravgopi123** [comment]
@PramodSSImmaneni : Thanks for updating. Wished Jira had same inforamtion

**Comment by chinmaykolhatkar** [comment]
@gauravgopi123 That's my bad. I've updated the Jira description for future reference.

**Pull request merged**
