### PR TITLE
APEXMALHAR-1993 & 1994: Fix for offset storage and reporting in kafka input operator

### PR DESCRIPTION
**Pull request by pramodin**

### CODE REVIEW

**Comment by pramodin** [comment]
@tweise @siyuanh please see, these issues are blocking an application deployment

**Comment by gauravgopi123** [comment]
@PramodSSImmaneni : Can you please add test case for this?

**Comment by pramodin** [comment]
@gauravgopi123 The testss in OffsetManagerTest cover it

**Comment by pramodin** [comment]
The test in OffsetManager may have succeeded earlier if timing was right, it will always succeed now. The tests weren't being called because of this being in contrib.

**Pull request merged**
