### PR TITLE
Implement semi-join operator with two input tables

### PR DESCRIPTION
**Pull request by d9liang**
Please review.

### CODE REVIEW

**Comment by otterc** [comment]
Is this a left-join implementation? This is a simple implementation over an application window. @chaithu14 has worked on an implementation which does join over much larger time windows. We are working to pull that change in. 
Meanwhile can we change the name here to call it 'SimpleLeftJoin"?

**Comment by d9liang** [comment]
@chandnisingh No this is not a left-join or left-outer-join. In semi-join only the joined rows from the left table are returned. However, in a left-outer-join, all the rows from left table will be returned (also padding with nulls for columns from the right table when not joined).

**Comment by otterc** [comment]
I see. Can you please explain a little bit about what semi-join is in the operator. Maybe a link will be helpful.

**Comment by d9liang** [comment]
@chandnisingh I've added sample cases in the Jira page

https://malhar.atlassian.net/projects/MLHR/issues/MLHR-1813

You can also find more info here:
http://docs.oracle.com/cd/B28359_01/server.111/b28286/statements_10002.htm#i2166436

**Comment by otterc** [comment]
@d9liang Can you please add the link to the info in the javadoc for this operator. Thanks.

**Comment by d9liang** [comment]
@chandnisingh I've added a link to the info in operator's Javadoc.

**Comment by otterc** [comment]
@d9liang the license check is failing. Can you please check?

**Comment by d9liang** [comment]
@chandnisingh I couldn't figure out what's wrong with the build, as it still fails even after removing the recent code with link info at javadoc. Please advise. I will add back the link info within javadoc section.

**Comment by otterc** [comment]
@d9liang I see this is not a problem with this pull request then. Please squash your changes and I will pull them in

**Comment by d9liang** [comment]
@chandnisingh PR squashed.

**Pull request merged**
