### PR TITLE
APEXMALHAR-1998 Use 2GB for kafka unit test so Travis can pass the test

### PR DESCRIPTION
**Pull request by davidyan74**

### CODE REVIEW

**Comment by davidyan74** [comment]
Do not merge unless Travis passes the check.

**Comment by siyuanh** [comment]
Is there any memory leak from the unit test?

**Comment by davidyan74** [comment]
@siyuanh, I don't know whether there is memory leak, but the kafka unit test fails in Travis CI because of not enough memory, and in my environment, the kafka unit test takes a long time to finish, albeit successfully.

**Comment by davidyan74** [comment]
@vrozov or @tweise or @siyuanh: since this passes in Travis, please merge.

**Pull request merged**
