### PR TITLE
APEXMALHAR-2272 : Fixed sequentialFileRead on FSInputModule

### PR DESCRIPTION
**Pull request by yogidevendra**

### CODE REVIEW

**Comment by yogidevendra** [comment]
@DT-Priyanka Could you please review this?

**Comment by DT-Priyanka** [comment]
Looks good to me, other that spelling mistake which Thomas and Ram pointed out.
Can you open a jira for spelling mistake so that we can track it?

**Comment by DT-Priyanka** [comment]
I will merge in couple of days if noone has any objection.

**Review by tweise — CHANGES_REQUESTED** [review]
Please address the comments. Fix spelling (including documentation) and mark it evolving.

**Review by DT-Priyanka — CHANGES_REQUESTED** [review]
We should mark FSInputModule class as "evolving"

**Comment by yogidevendra** [comment]
@DT-Priyanka Updated the PR as per the feedback.

**Comment by DT-Priyanka** [comment]
The commit message has spell mistake for sequencial, @yogidevendra  check if you can amend commit message. I will go ahead with merge.

**Comment by tweise** [comment]
@DT-Priyanka why is the PR still open? Please see instructions for merging PRs on contributor page.

**Comment by yogidevendra** [comment]
@tweise There was some glitch due to git config mismatch for @DT-Priyanka. PR is merged in apache/master but it is not reflected as merged on github. Should we just close this PR on github (since apache logs shows PR merged)? OR should we revert the commit on apache and redo the merging exercise?

**Comment by tweise** [comment]
You should close this PR. This would have happened automatically was the merge done correctly.

**Comment by yogidevendra** [comment]
PR is merged on the apache as per APEXMALHAR-2272. Thus, closing this PR. [Ideally, this should have been closed automatically.]

**Pull request closed without merging**
