### PR TITLE
APEXMALHAR-2104 GenericFileOutputOperator is not abstract.

### PR DESCRIPTION
**Pull request by tweise**
Follow-up from #304, also fixes spaces and EOL.
@PramodSSImmaneni please merge

### CODE REVIEW

**Comment by gauravgopi123** [comment]
@tweise : Small issue.. Branch name is not according to guidelines

**Comment by tweise** [comment]
@gauravgopi123 what branch name? Do you mean the since tag?

**Comment by gauravgopi123** [comment]
@tweise : Branch name of PR.. I think it should be tweise:APEXMALHAR-2104 instead of tweise:master

**Comment by tweise** [comment]
That's correct. The assumption is that this gets merged right away (hint, hint.. :) and so I won't mess up my own PR by putting more changes into master.

**Pull request merged**
