### PR TITLE
APEXMALHAR-2510 adding all matching keys to result for join accumulation

### PR DESCRIPTION
**Pull request by KapoorHitesh**
@chinmaykolhatkar @ShunxinLu please review.

### CODE REVIEW

**Comment by ShunxinLu** [comment]
I think this is good. Thanks for the quick response.

**Comment by chinmaykolhatkar** [comment]
@Hitesh-Scorpio Can you check why the builds are failing?

**Comment by KapoorHitesh** [comment]
@chinmaykolhatkar  In Jenkins I am getting the build success message but still it is failing with "Warning: this build has no associated authentication, so build permissions may be lacking, and downstream projects which cannot even be seen by an anonymous user will be silently skipped
Finished: UNSTABLE".

Travis is passing here as well as on my local machine. Should I close and reopen the PR?

--Hitesh

**Comment by ShunxinLu** [comment]
@Hitesh-Scorpio I tested the fix in an application. Even though the previous problem we discussed is fixed, the app still seems to be still unable to behave correctly. I dug deeper into the new problem and it looks like that Kryo creates couple more instances of join accumulation by calling its default constructor. And this wipes out all the keys (left, right) stored in the first place, so that when doing accumulation, the left and right keys are always empty, and therefore the inner join is not being performed correctly. 
Making the default constructor do nothing and changing the member fields of AbstractPojoJoin to static kind of fix the issue. But I wonder if that's the correct way to do this. Could you please take a look into this problem as well? Thanks!

**Comment by KapoorHitesh** [comment]
@ShunxinLu  I think you can open a separate JIRA for that issue and we can discuss it separately.

**Comment by ShunxinLu** [comment]
@Hitesh-Scorpio Agree. Will open a JIRA shortly. @chinmaykolhatkar I believe this PR is ready to merge.

**Comment by chinmaykolhatkar** [comment]
@Hitesh-Scorpio @ShunxinLu  Thanks for resolution on this. I'll merge this PR in couple of days.

**Review by chinmaykolhatkar — APPROVED** [review]

**Comment by vrozov** [comment]
@Hitesh-Scorpio @ShunxinLu @chinmaykolhatkar closed due to inactivity

**Pull request closed without merging**
