### PR TITLE
APEXMALHAR-2003 NPE in blockMetaDataIterator after recovery

### PR DESCRIPTION
**Pull request by otterc**

### CODE REVIEW

**Comment by otterc** [comment]
@vrozov @bhupeshchawda please review and merge

**Comment by otterc** [comment]
CI failed because of unrelated test

**Comment by otterc** [comment]
Test case added please merge

**Comment by otterc** [comment]
build failing because of kafka module tests

**Comment by tweise** [comment]
please close/reopen to trigger CI

**Pull request closed without merging**
