### PR TITLE
MLHR-1931 #resolve

### PR DESCRIPTION
**Pull request by otterc**
@tushargosavi Please review and merge

### CODE REVIEW

**Comment by tweise** [comment]
Why is this not done using the reader instead of adding code to each implementation? Also please use human readable commit messages and pull request descriptions.

**Comment by otterc** [comment]
Updated the commit message.
The change adds retrieving values as Slice with readFully. 
There is already a comment on existing readFully(...) -

```
    //Move to
    // void readFully(TreeMap<Slice, Slice> data) throws IOException;
       void readFully(TreeMap<Slice, byte[]> data) throws IOException;
```

Also when next reads value as Slice, then readFully should be consistent with it.

**Comment by tweise** [comment]
Would like to understand what this is needed for.

**Comment by otterc** [comment]
I need values as Slice so I don't have to convert it to byte[]. 
When reading value of a particular key,  FileReader.next(Slice key, Slice value) let's me do that.
However the existing readFully expects the value as byte[]. There was already a comment there that it should move to `(TreeMap<Slice, Slice>)` so since I needed it now I added that.

**Comment by tweise** [comment]
The comment was move, not duplicate :-)

**Comment by otterc** [comment]
I can move it though if later HDHT uses this API in Malhar, then it will have to change its implementation and so I didn't remove the existing method.

**Comment by otterc** [comment]
Also because of type erasure I can't add another method 
`readFully(TreeMap<Slice, Slice> data)`

**Comment by tweise** [comment]
The class is "new" in Malhar and we should make the changes to the old code unless you foresee a real problem doing so.

**Comment by otterc** [comment]
All right. Moved the method instead of adding another one.

@tushargosavi @tweise please merge

**Pull request merged**
