### PR TITLE
APEXMALHAR-2093 Removed usages of Idempotent Storage Manager

### PR DESCRIPTION
**Pull request by otterc**
This is a backward incompatible change so added exclusions to japicmp plugin configuration.

### CODE REVIEW

**Comment by sandeshh** [comment]
Is there a strong reason to make the backward incompatible change? 

How about following
1. Mark the idempotent Storage manager api deprecated.
2. IdempotentStorageManager will use the WindowDataManager ( Proxy pattern )
3. Expose WindowDataManager api

**Comment by otterc** [comment]
@sandeshh 
- We have already marked the idempotent storage manager api deprecated.
- The 2nd point can be done but there will be so much of unused code because IdempotentStorageManager is not Evolving and has to be backward compatible.
- WindowDataManager API is already exposed.

**Comment by tweise** [comment]
@chandnisingh please rebase

**Comment by otterc** [comment]
@tweise rebased

**Pull request merged**
