### PR TITLE
SPOI-7087 #resolve #comment Add JDBC dimension output operator to Malhar

### PR DESCRIPTION
**Pull request by brightchen**

### CODE REVIEW

**Comment by brightchen** [comment]
The RuntimeException or InterruptedException should not due to this change:
2016-02-22 20:49:11,656 [main] INFO  jms.AbstractJMSInputOperator endWindow - confirm recovery of 1 for 1 does not exist
java.lang.RuntimeException: fail ack
    at com.datatorrent.lib.io.jms.JMSStringInputOperatorTest$1.acknowledge(JMSStringInputOperatorTest.java:145)
    at com.datatorrent.lib.io.jms.AbstractJMSInputOperator.endWindow(AbstractJMSInputOperator.java:367)
    at com.datatorrent.lib.io.jms.JMSStringInputOperatorTest.testFailureAfterPersistenceAndBeforeRecovery(JMSStringInputOperatorTest.java:158)

java.lang.InterruptedException: sleep interrupted
    at java.lang.Thread.sleep(Native Method)
    at com.datatorrent.lib.io.fs.FileSplitter$TimeBasedDirectoryScanner.run(FileSplitter.java:713)

**Comment by brightchen** [comment]
@chandnisingh Could you please review and merge? just move a file from Tim's repository to malhar

**Comment by ilooner** [comment]
hey @brightchen I'll take a look. I'll merge it shortly. Before I merge I'll annotate the operator as Evolving as there will likely be changes. I'll also create a ticked to add a unit test.

Thanks,
Tim

**Comment by ilooner** [comment]
@brightchen this PR was merged. Please close this PR

**Pull request closed without merging**
