### PR TITLE
APEXMALHAR-2550 Made NycTaxiDataReader and NycTaxiCsvParser more resi…

### PR DESCRIPTION
**Pull request by davidyan74**
…lient to data with bad format

@tweise Please take a look.

### CODE REVIEW

**Comment by davidyan74** [comment]
Failing test on Travis is completely unrelated:
org.apache.hadoop.io.file.tfile.DTFileTest
seekDTFile(org.apache.hadoop.io.file.tfile.DTFileTest)  Time elapsed: 0.322 sec  <<< FAILURE!
java.lang.AssertionError: Cache contains one more blocks  expected:<5> but was:<6>
	at org.apache.hadoop.io.file.tfile.DTFileTest.seekDTFile(DTFileTest.java:189)

**Comment by davidyan74** [comment]
test this please

**Comment by tweise** [comment]
tes this please

**Comment by tweise** [comment]
test this please

**Comment by tweise** [comment]
test this please

**Pull request merged**
