### PR TITLE
[REVIEW-ONLY] Fixed python implementation for Apache Apex

### PR DESCRIPTION
**Pull request by patilvikram**
This PR includes both stateless + stateful support based on High-Level APIs.

### CODE REVIEW

**Comment by patilvikram** [comment]
@PramodSSImmaneni  @tushargosavi 
This PR includes all changes for python and we can reject earlier PR and move over to this one.

**Comment by tweise** [comment]
Why are you opening another PR? Keep on working on the existing PR to retain the communication trail.

**Comment by tweise** [comment]
Also see http://apex.apache.org/contributing.html#opening-pull-requests for how to open PRs.

**Comment by patilvikram** [comment]
@tweise Actually older PR is not completely reviewed and I finished some initial work for supporting windowed operator in python using high-level apis. While doing that I have refactored lots of code and cleaned it, also included comments from already opened PR.

**Comment by tweise** [comment]
@patilvikram PRs are updated with changes as they are reviewed, so that there is a single thread to follow the work. If you are not sure how that works after reading the guidelines, please consult other contributors in your office. Close #613 if you wan to continue here, but then please stick with it.

**Comment by patilvikram** [comment]
I have merged all changes here to #613  so closing this now.

**Pull request closed without merging**
