### PR TITLE
APEXMALHAR-2491 Changes to shutdown the controller after completion of waittime in GenericFileOutputOperatorTest

### PR DESCRIPTION
**Pull request by ajaygit158-zz**

### CODE REVIEW

**Comment by ajaygit158-zz** [comment]
@tushargosavi Kindly review

**Comment by vrozov** [comment]
@ajaygit158 Please see http://apex.apache.org/contributing.html

**Comment by ajaygit158-zz** [comment]
Corrected the commit message to include JIRA ID

**Review by tushargosavi — APPROVED** [review]
LGTM

**Comment by vrozov** [comment]
Rebase against upstream/master

**Comment by ajaygit158-zz** [comment]
Rebase done

**Pull request merged**
