### PR TITLE
APEXMALHAR-2129 removed moving time boundaries periodically and async…

### PR DESCRIPTION
**Pull request by otterc**
…hrnously based on system time

### CODE REVIEW

**Comment by otterc** [comment]
@bhupeshchawda @ilooner 
Please review since you are familiar with this code.

**Comment by ilooner** [comment]
@chandnisingh lgtm

**Comment by bhupeshchawda** [comment]
@chandnisingh lgtm too.

Just a thought: `getTimeBucketFor()` also moves bucket boundaries in addition to getting the time bucket which seems like a unknown side effect. Can we perhaps rename it to something like:  `getTimeBucketAndAdjustBoundaries()`

**Comment by otterc** [comment]
Addressed the review comments. Please merge.

**Pull request merged**
