### PR TITLE
APEXMALHAR-2355 Added schema annotation

### PR DESCRIPTION
**Pull request by pramodin**
@yogidevendra @pradeepdalvi please see

### CODE REVIEW

**Comment by yogidevendra** [comment]
Changes looks OK. But, jenkins build has some failing tests not related to this.

**Comment by yogidevendra** [comment]
@PramodSSImmaneni 
APEXMALHAR-2357 has fixed the tests causing this jenkins failure. Could you please rebase this against updated master? Let us see if travis, jenkins pass through fine.

**Comment by yogidevendra** [comment]
@PramodSSImmaneni Any update?

**Comment by vrozov** [comment]
@PramodSSImmaneni @yogidevendra closed due to inactivity

**Pull request closed without merging**
