### PR TITLE
APEXMALHAR-2227 Index out of Bound Exception fix in Kafka input

### PR DESCRIPTION
**Pull request by otterc**
@siyuanh @tweise

### CODE REVIEW

**Comment by siyuanh** [comment]
@chandnisingh The test fails because of FileNotFoundException which is related to your FSWindowManager change. Would you please take a look? Thanks

**Comment by otterc** [comment]
@siyuanh which test fails?

**Comment by otterc** [comment]
@siyuanh fixed the issue.

**Comment by tweise** [comment]
Tested with 

```
cd contrib
mvn clean test -Dtest=Kafka* -DskipTests=false
```

**Comment by tweise** [comment]
@siyuanh can you please check that the CI covers this for the 0.9 connector?

**Pull request merged**
