### PR TITLE
APEXMALHAR-2084: Fixed getters and setters for kafka clusters and topics

### PR DESCRIPTION
**Pull request by bhupeshchawda**

### CODE REVIEW

**Comment by bhupeshchawda** [comment]
Added validation for topics

**Comment by gauravgopi123** [comment]
@bhupeshchawda : Can you please elaborate why this change is required? Didn't find much on Jira.

**Comment by bhupeshchawda** [comment]
@gauravgopi123 : Here is some discussion that happened on the dev@apex list:
http://mail-archives.apache.org/mod_mbox/incubator-apex-dev/201605.mbox/%3CCAHvM9d3QO%3D%3DRiyGs_MEda0Nz-4CXR1is1sK%3D%3DyswcKyTVCeuPg%40mail.gmail.com%3E

This is more to do with keeping accessors consistent for the sake of external tools that may be integrated with Apex operators.

**Comment by gauravgopi123** [comment]
Although this is merged, please make sure that branch names follow the contribution guidelines (http://apex.apache.org/contributing.html).

**Comment by tweise** [comment]
@bhupeshchawda how does this change affect configuration in XML?

**Comment by tweise** [comment]
The merge is backed out. Please reopen the PR and give due time to review and address comments.

**Comment by bhupeshchawda** [comment]
Sure, will take this up on the dev mailing list.

**Pull request merged**
