### PR TITLE
MLHR-1946 #resolve #comment Marked WindowUtils as unstable.

### PR DESCRIPTION
**Pull request by ilooner**

### CODE REVIEW

**Comment by ilooner** [comment]
@chandnisingh Please review

**Comment by otterc** [comment]
Don't think we need to mark this util as unstable. Why will you want to mark it unstable?

**Comment by ilooner** [comment]
@chandnisingh The location of the class and the signature of the methods may change if it is used in @siyuanh api changes.

**Comment by otterc** [comment]
I think then we need to go with performing semver only for @Stable classes. Don't think it is a good idea to make it Unstable. There is some time for high level api

**Pull request closed without merging**
