### PR TITLE
APEXMALHAR-2458 remove hard coded port numbers from Kafka example tests.

### PR DESCRIPTION
**Pull request by tweise**
@sandeshh please review

### CODE REVIEW

**Comment by tweise** [comment]
https://builds.apache.org/job/Apex_Malhar_PR/1570/org.apache.apex$malhar-examples-kafka/console

**Comment by tweise** [comment]
@sandeshh @chaithu14 can one of you merge this to fix the CI issues

**Comment by chaithu14** [comment]
@tweise Changes are LGTM. APEXMALHAR-2162 is related to operator unit tests. So, Could you please create a new JIRA or sub-task to APEXMALHAR-2162 for this PR.

**Comment by tweise** [comment]
I changed the JIRA number. This isn't a subtask, it was missed when the examples were added.

**Pull request merged**
